### ISSUE TITLE
Facing while passing decimal values 

### ISSUE THREAD

**Issue by amarjaincoredofi** [Paybyway/visma-pay-php-lib#1]
Hi Team, 

I am facing problem while passing decimal values in "addProductMethod" method. Please find example below. 

        $vismaPay->addCharge(array(
                  'order_number' => '1234',
                  'amount' => 148.80,
                  'currency' => 'EUR'
         ));

        $vismaPay->addCustomer(array(
            'name' => 'test',
            'contactName' => 'test',
            'address_street' => 'test',
            'address_city' => 'test',
            'address_zip' => 'test'
        ));

        $vismaPay->addProduct(array(
            'id' => 'membership',
            'title' => 'entrepreneur',
            'count' => 1,
            'pretax_price' => 120,
            'tax' => 24,
            'price' => 148.80,
            'type' => 1
        ));

      $paymentMethod = array(
            'return_url' => $returnUrl,
            'notify_url' => $returnUrl,
            'type' => 'e-payment',
            'lang' => 'fi'
        );

     addPaymentMethod($paymentMethod);

     $result = $vismaPay->createCharge();

**Result:** 

**Exception:** stdClass Object ( [result] => 1 [errors] => Array ( [0] => The amount must be an integer. [1] => The product.price must contain only integers. ) )

any assistance you can provide would be greatly appreciated.

**Comment by kkopone** [comment]
Hi,

the amount is in fractional monetary units. 148.80 EUR would be then `14880`.
